[gravity]
domain = "gravity"
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapter_id = "stan_adapter"
adapter_name = "STAN Adapter"

[source]
config = "./settings/sources.json"
